# https://travis-ci.org/stormpath/stormpath-sdk-java
language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

install: echo "No need to run mvn install -DskipTests then mvn install.  Running mvn install."
script: mvn install

# Stormpath API Key configuration.
#
# If you want to use your own API Key:
#
# 1. Ensure you have the travis gem installed:
#
#     gem install travis
#
# 2. change the value of STORMPATH_API_KEY_ID below to match your own API Key ID
#
# 3. Change the 'secure' value to be the output of the following command:
#
#     travis encrypt STORMPATH_API_KEY_SECRET=YOUR_API_KEY_SECRET
#
# where YOUR_API_KEY_SECRET is your actual API Key secret value.  Once the above command finishes, replace the secure
# value below with the output of that command.
env:
  global:
    - STORMPATH_API_KEY_ID=CN5D6CEHMI7M1HVSBW74N626X
    - secure: "W7X8AjOaQRmrzfZ3G2wn5rxld1aw5osYLKWY98U6hU5jy148HLzJ1s+v/RdydAAB2d4xuYvr5WrUEaF/eHJ4AF0zBNDwst84VHUxT3yTzBFVHgnd/rbn8AMpITQtwIiXEr+hMK3cAVXwZtZ+mLmkllyf48Myk75QDxwwJnKS2UA="

