# https://travis-ci.org/stormpath/stormpath-sdk-java
language: java

# http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8

install: echo "No need to run mvn install -DskipTests then mvn install.  Running mvn install."
script: mvn install

# Stormpath API Key configuration.
#
# If you want to use your own API Key:
#
# 1. Ensure you have the travis gem installed:
#
#     gem install travis
#
# 2. change the value of STORMPATH_API_KEY_ID below to match your own API Key ID
#
# 3. Change the 'secure' value to be the output of the following command:
#
#     travis encrypt STORMPATH_API_KEY_SECRET=YOUR_API_KEY_SECRET
#
# where YOUR_API_KEY_SECRET is your actual API Key secret value.  Once the above command finishes, replace the secure
# value below with the output of that command.
env:
  global:
  - STORMPATH_API_KEY_ID=58J8VBZG5WK9CYTEYPZSQX670
  - secure: "ZAs6XDgRX1YIZAKf0IcR6DlfQtGLKJS5fyTOextZsRW3MCwu7WTBe5v6dAS6xoLqZ0iEkICMdIRhs+6DQEW6rju/W39mjxe8HJEcMNI+wZyW+rZ+j7NmPkjovMO+XbiR0aVVvn7ZGjWEKdozCTBVtJSLd8YVHh6Ey+yxOdDoc1A="
