language: java
sudo: false
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
env:
  global:
  - STORMPATH_API_KEY_ID=5ZAFM5P52226F24AW0IBKBRW8
  - STORMPATH_API_KEY_ID_TWO_APP=254JEPOVDMXC7PX9G6V54AQDV
  - AWS_ACCESS_KEY_ID=AKIAINZJPJUSAC3U7BYQ
  - PATH=~/usr/local/aws:~/usr/local/aws/bin:$PATH
  - secure: cOjEEqUxs8bUC0xpEDHbdl6SE/rYUh27fI+4g3DjRB+afewd9RYOywl6IDNFUKjxuXh4qCOm6WM1m13ckL7ZHeUJeU3H3WatQookE0+nEn8sbKN55hqejG6sKfatElorCY2Tik6EayOsYj5UNAbj2l/cinZTqN8alEQ81SBUEiI=
  - secure: EGnppv9jq0yabOXi4KcSPsXziPPs9x7rjd1HHNdg1xMeike9kEmzNP4FJQpYkHqqdgoe9qETBrB+gcMS+3lcqFt9rvsgNVFXEWDMfRlgTkK4Se/vp8HomIMz68Sa6aG9SKDJJpiyoCUCAL1fqkDADz1dEvbB8v3QU4+11zNRVCQ=
  - secure: X1ATGvagtlk+RbCO3rG8ieR+5YCcrXIzlhsOinWdgIMOGf+lojuBlA6mCzQjCu6WrbdddZx+PQBOFP+Z6Ztj8jWunXF+lA5fkcwHB4OWwQ349IFCudfoF3igYkBgJ6LV9iw1St48EZQUOlBUu8Gm7ABgbVSR+S8G6aA0kieKFVg=    
before_install:
- openssl aes-256-cbc -K $encrypted_da634cfd642b_key -iv $encrypted_da634cfd642b_iv
  -in deployKey_stormpath_github_io_id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- openssl aes-256-cbc -K $encrypted_0b7f5d43be1f_key -iv $encrypted_0b7f5d43be1f_iv 
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mkdir -p ~/.stormpath/clover
- cp clover.license ~/.stormpath/clover
- cp .netrc ~/
- export RELEASE_VERSION="$(mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate
  -Dexpression=project.version|grep -Ev '(^\[|Download\w+:)')"
- export IS_RELEASE="$([ ${RELEASE_VERSION/SNAPSHOT} == $RELEASE_VERSION ] && [ $TRAVIS_BRANCH == 'master' ] && echo 'true')"
- export BUILD_DOCS="$([ $TRAVIS_JDK_VERSION == 'oraclejdk8' ] && echo 'true')"
- export RUN_ITS="$([ $TRAVIS_JDK_VERSION == 'openjdk7' ] && echo 'true')"
install:
- test -z "$BUILD_DOCS" || pip -q install --user sphinx
- test -z "$RUN_ITS" || ./install_aws_cli.sh
script:
- test -z "$RUN_ITS" || mvn -Pclover.all -DskipITs=false -q install
- test -n "$RUN_ITS" || mvn -q install
- test -z "$BUILD_DOCS" || ./build_docs.sh
after_success:
- test -z "$BUILD_DOCS" || test -z "$IS_RELEASE" || ./publish_docs.sh
- test -z "$RUN_ITS" || ./publish_coverage_report.sh
notifications:
  hipchat:
    on_success: always
    on_failure: always
    rooms:
      secure: WXJLZTnleKQd5DIfdPSNYk4ZT7bssV9esdaacZjwb9sdKLZAQ+ujL97uuVK4oDMbua9XJxYTsKK45QQp56+PgJc4KG0Regvs/e7NtoxahrNnpsHCob4+Hc2MSmFfJgsdAQ9dFemNZ3BQ2ec1gO6SToYk+7pwMPScUYnmAOrsHjU=
    template:
      '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)' 
    format: html
  slack:
    secure: INiA7V4aXvimkImaErVH94ZSmFNuOgun9aurmf3BiE2Qq0EfNiEaWK9pp6hfkv+wSls4LXNDLaYVzdoMECVLh+Dv9VLHIABnaNEmMStXUlyZ+sOpdayl/47gnNr0G1cr06eqbikGVqWtQaxDz2Psaejq2D/6WYw5Vnqk4BjWQHw=
